export default {
    LOAD:         "LOAD",
    LOAD_SUCCESS: "LOAD_SUCCESS",
    LOAD_FAILURE: "LOAD_FAILURE",

    LOAD_EPISODE:         "LOAD_EPISODE",
    LOAD_EPISODE_SUCCESS: "LOAD_EPISODE_SUCCESS",
    LOAD_EPISODE_FAILURE: "LOAD_EPISODE_FAILURE",
};